// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.msl521.met.domain;

import java.lang.String;

privileged aspect Organization_Roo_JavaBean {
    
    public String Organization.getName() {
        return this.name;
    }
    
    public void Organization.setName(String name) {
        this.name = name;
    }
    
}
