// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.msl521.met.domain;

import java.lang.Long;

privileged aspect Party_Roo_JavaBean {
    
    public Long Party.getId() {
        return this.id;
    }
    
    public void Party.setId(Long id) {
        this.id = id;
    }
    
}
