// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.msl521.met.domain;

import com.github.msl521.met.domain.Insurer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InsurerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InsurerDataOnDemand: @Component;
    
    private Random InsurerDataOnDemand.rnd = new SecureRandom();
    
    private List<Insurer> InsurerDataOnDemand.data;
    
    public Insurer InsurerDataOnDemand.getNewTransientInsurer(int index) {
        Insurer obj = new Insurer();
        setName(obj, index);
        return obj;
    }
    
    public void InsurerDataOnDemand.setName(Insurer obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Insurer InsurerDataOnDemand.getSpecificInsurer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Insurer obj = data.get(index);
        return Insurer.findInsurer(obj.getId());
    }
    
    public Insurer InsurerDataOnDemand.getRandomInsurer() {
        init();
        Insurer obj = data.get(rnd.nextInt(data.size()));
        return Insurer.findInsurer(obj.getId());
    }
    
    public boolean InsurerDataOnDemand.modifyInsurer(Insurer obj) {
        return false;
    }
    
    public void InsurerDataOnDemand.init() {
        data = Insurer.findInsurerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Insurer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.github.msl521.met.domain.Insurer>();
        for (int i = 0; i < 10; i++) {
            Insurer obj = getNewTransientInsurer(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
