// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.msl521.met.domain;

import com.github.msl521.met.domain.OfficeVisit;
import com.github.msl521.met.domain.Patient;
import com.github.msl521.met.domain.PatientDataOnDemand;
import com.github.msl521.met.domain.Provider;
import com.github.msl521.met.domain.ProviderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OfficeVisitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OfficeVisitDataOnDemand: @Component;
    
    private Random OfficeVisitDataOnDemand.rnd = new SecureRandom();
    
    private List<OfficeVisit> OfficeVisitDataOnDemand.data;
    
    @Autowired
    private PatientDataOnDemand OfficeVisitDataOnDemand.patientDataOnDemand;
    
    @Autowired
    private ProviderDataOnDemand OfficeVisitDataOnDemand.providerDataOnDemand;
    
    public OfficeVisit OfficeVisitDataOnDemand.getNewTransientOfficeVisit(int index) {
        OfficeVisit obj = new OfficeVisit();
        setPatient(obj, index);
        setProvider(obj, index);
        return obj;
    }
    
    public void OfficeVisitDataOnDemand.setPatient(OfficeVisit obj, int index) {
        Patient patient = patientDataOnDemand.getRandomPatient();
        obj.setPatient(patient);
    }
    
    public void OfficeVisitDataOnDemand.setProvider(OfficeVisit obj, int index) {
        Provider provider = providerDataOnDemand.getRandomProvider();
        obj.setProvider(provider);
    }
    
    public OfficeVisit OfficeVisitDataOnDemand.getSpecificOfficeVisit(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        OfficeVisit obj = data.get(index);
        return OfficeVisit.findOfficeVisit(obj.getId());
    }
    
    public OfficeVisit OfficeVisitDataOnDemand.getRandomOfficeVisit() {
        init();
        OfficeVisit obj = data.get(rnd.nextInt(data.size()));
        return OfficeVisit.findOfficeVisit(obj.getId());
    }
    
    public boolean OfficeVisitDataOnDemand.modifyOfficeVisit(OfficeVisit obj) {
        return false;
    }
    
    public void OfficeVisitDataOnDemand.init() {
        data = OfficeVisit.findOfficeVisitEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'OfficeVisit' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.github.msl521.met.domain.OfficeVisit>();
        for (int i = 0; i < 10; i++) {
            OfficeVisit obj = getNewTransientOfficeVisit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
