// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.msl521.met.domain;

import com.github.msl521.met.domain.ProviderTypeDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProviderTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProviderTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProviderTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProviderTypeIntegrationTest: @Transactional;
    
    @Autowired
    private ProviderTypeDataOnDemand ProviderTypeIntegrationTest.dod;
    
    @Test
    public void ProviderTypeIntegrationTest.testCountProviderTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", dod.getRandomProviderType());
        long count = com.github.msl521.met.domain.ProviderType.countProviderTypes();
        org.junit.Assert.assertTrue("Counter for 'ProviderType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testFindProviderType() {
        com.github.msl521.met.domain.ProviderType obj = dod.getRandomProviderType();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to provide an identifier", id);
        obj = com.github.msl521.met.domain.ProviderType.findProviderType(id);
        org.junit.Assert.assertNotNull("Find method for 'ProviderType' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProviderType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testFindAllProviderTypes() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", dod.getRandomProviderType());
        long count = com.github.msl521.met.domain.ProviderType.countProviderTypes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProviderType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.github.msl521.met.domain.ProviderType> result = com.github.msl521.met.domain.ProviderType.findAllProviderTypes();
        org.junit.Assert.assertNotNull("Find all method for 'ProviderType' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProviderType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testFindProviderTypeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", dod.getRandomProviderType());
        long count = com.github.msl521.met.domain.ProviderType.countProviderTypes();
        if (count > 20) count = 20;
        java.util.List<com.github.msl521.met.domain.ProviderType> result = com.github.msl521.met.domain.ProviderType.findProviderTypeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProviderType' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProviderType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testFlush() {
        com.github.msl521.met.domain.ProviderType obj = dod.getRandomProviderType();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to provide an identifier", id);
        obj = com.github.msl521.met.domain.ProviderType.findProviderType(id);
        org.junit.Assert.assertNotNull("Find method for 'ProviderType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProviderType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProviderType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testMerge() {
        com.github.msl521.met.domain.ProviderType obj = dod.getRandomProviderType();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to provide an identifier", id);
        obj = com.github.msl521.met.domain.ProviderType.findProviderType(id);
        boolean modified =  dod.modifyProviderType(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.github.msl521.met.domain.ProviderType merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProviderType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", dod.getRandomProviderType());
        com.github.msl521.met.domain.ProviderType obj = dod.getNewTransientProviderType(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProviderType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProviderType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProviderTypeIntegrationTest.testRemove() {
        com.github.msl521.met.domain.ProviderType obj = dod.getRandomProviderType();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProviderType' failed to provide an identifier", id);
        obj = com.github.msl521.met.domain.ProviderType.findProviderType(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProviderType' with identifier '" + id + "'", com.github.msl521.met.domain.ProviderType.findProviderType(id));
    }
    
}
